# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a32eba2c8cdb183d8901c6dd491eebe3af5ce2ff274b41a63e711c1e963cc48fc3da428b0e79392cbd839f784dbb957d6271059e82aefe60710cd1734531afb0

test:
  secret_key_base: d1acf502328df5d1578c3b5e1bdb8115ee252fc07b52759c0555df0a03bc7b3583917036b33584d6a275f1183bcf2b6b648a239d54891a723023b14842a45e6d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
